### ISSUE TITLE
Create SQL schema 

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-014#15]
- [x] Schema is in GitHub
- [x] Image with schema is in Wiki

**Comment by fred-navruzov** [comment]
1) Add page on Wiki (https://github.com/ITsvetkoFF/Kv-014/wiki/DB-Schema-%28ER-model%29)
2) Add db_creation script as well as some data fill in (https://github.com/ITsvetkoFF/Kv-014/tree/develop/SQL%20data)
2.1) However, some work still needs to be done (insert script into other tables is incomplete)
