### ISSUE TITLE
US08 - Employees

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-014#37]
- [x] Create feature branch
- [x] _Sign up_. Back-end: implement employee creation
- [x] _Sign up_. Back-end: add REST request for employee creation
- [x] _Sign up_. Front-end: create sign up form
- [x] _Sign up_. Front-end: send employee creation REST request and handle response
- [x] _Log in_. Front-end: create log in form
- [x] _Log in_. Back-end: implement authentication
- [x] _Log in_. Back-end: add login REST
- [x] _Log in_. Front-end: show "logged in user" form on all pages
- [x] _Log in_. Front-end: send login REST and handle response
- [x] _List of employees_. Front-end: create list of employees table
- [x] _List of employees_. Back-end: add REST request to get all employees
- [x] _List of employees_. Back-end: implement get all employees specification
- [x] _List of employees_. Front-end: send list of all employees REST request
- [x] _List of employees_. Front-end: handle list of all employees REST response and display list in the table
- [ ] _List of employees_. Back-end: add REST request to get employees by role
- [ ] _List of employees_. Back-end: implement get employees by role specification
- [ ] _List of employees_. Front-end: add component for filtering employees by role 
- [ ] _List of employees_. Front-end: send get employees by role REST request and handle response
- [x] _List of employees_. Front-end: add component for changing employee role
- [x] _List of employees_. Back-end: add REST request to edit employee role
- [ ] _List of employees_. Back-end: implement edit role logic
- [ ] _List of employees_. Front-end: send edit role REST request and handle response
- [ ] _List of employees_. Front-end: implement employees sorting by parameters

**Comment by juliab** [comment]
- [ ] Create feature branch
- [ ] _Sign up_. Back-end: implement employee creation
- [ ] _Sign up_. Back-end: add REST request for employee creation
- [ ] _Sign up_. Front-end: create sign up form
- [ ] _Sign up_. Front-end: send employee creation REST request and handle response
- [ ] _Log in_. Front-end: create log in form
- [ ] _Log in_. Back-end: implement authentication
- [ ] _Log in_. Back-end: add login REST
- [ ] _Log in_. Front-end: show "logged in user" form on all pages
- [ ] _Log in_. Front-end: send login REST and handle response
- [ ] _List of employees_. Front-end: create list of employees table
- [ ] _List of employees_. Back-end: add REST request to get all employees
- [ ] _List of employees_. Front-end: send list of all employees REST request
- [ ] _List of employees_. Front-end: handle list of all employees REST response and display list in the table
- [ ] _List of employees_. Back-end: add REST request to get employees by role
- [ ] _List of employees_. Front-end: add filter employees by role component
- [ ] _List of employees_. Front-end: send get employees by role REST request and handle response
- [ ] _List of employees_. Front-end: add change employee role component
- [ ] _List of employees_. Back-end: add REST request to edit employee role
- [ ] _List of employees_. Back-end: implement edit role logic
- [ ] _List of employees_. Front-end: send edit role REST request and handle response
- [ ] _List of employees_. Front-end: implement employees sorting by parameters
