### ISSUE TITLE
Specification's restriction type research

### ISSUE THREAD

**Issue by bcherniakh** [ITsvetkoFF/Kv-014#47]
Make a research about the best restriction object for Specification that'll work fine with Hibernate. (for e.g. org.hibernate.criterion.Criterion, HQL query or plain SQL query...)
- [ ] Restriction works correctly with the Repository API.

**Comment by JuliaAvdeionok** [comment]
Based on the information below, I vote for HQL!

Ahmad Reza Seddighi :"In general, the Criteria approach is less flexible and less powerful than HQL. Criteria queries are less readable and harder to understand than HQL queries. Typically, creating the right query with Criteria requires more effort. More importantly, Criteria queries cannot be declared in the mapping metadata, as HQL queries can. This may increase maintenance problems. 
Although HQL and Criteria queries are interchangeable, in some situations one is more fitting than the other. For instance, when query restrictions are constructed from user input, or when they change during application execution, it's better to use the Criteria API to create a query expression. HQL expressions are simple string literals whose syntax is checked at runtime, whereas the Criteria queries are Java objects that naturally are checked at compile time. Therefore, manipulating the string query expressions which are constructed from the user input, which might fail in some conditions, would be painful. Using Criteria, you can create nested, structured query expressions based on the data input by a user, which is a more convenient approach." (Spring Persistence with Hibernate)

Example for SQL:  select \* from contact where contact.FIRST_NAME="firstName" and LAST_NAME="lastName";

1.HQL:
   @Override
    public List<Contact> findByFirstANDLastNameHQL(String firstName, String lastName) {
        String hql = "from Contact c where c.firstName=:firstName and c.lastName=:lastName";
        org.hibernate.Query query= sessionFactory.getCurrentSession().createQuery(hql);
        query.setParameter("firstName", firstName);
        query.setParameter("lastName", lastName);
        return query.list();
    }

2.Criteria
    @Override
    public List<Contact> findByFirstNameANDLastNameCriteria(String firstName,String lastName) {
        Criteria criteria = sessionFactory.getCurrentSession().createCriteria(Contact.class);
        Criterion criterionFirstName = Restrictions.eq("firstName",firstName);
        criteria.add(criterionFirstName);
        Criterion criterionLastName = Restrictions.eq("lastName",lastName);
        criteria.add(criterionLastName);
        return criteria.list();
    }
